const express = require('express')
const mongoose = require('mongoose')
const userRouter = require('./controllers/users')
const loginRouter = require('./controllers/login')
const gameRouter = require('./controllers/game')
const adminRouter = require('./controllers/admin')
const config = require('./utils/config')
const middleware = require('./utils/middleware')
const cors = require('cors')
require('express-async-errors')

const app = express()

mongoose.connect(config.MONGODB_URI)
    .then(() => console.log('Connected to the DB'))
    .catch((e) => console.log(`Could not connect to the DB [${e.message}]`))

app.use(cors())
app.use(express.json())
app.use(express.static('build'))
app.use(middleware.tokenExtractor)
app.use(middleware.userExtractor)
app.use('/users', userRouter)
app.use('/login', loginRouter)
app.use('/game', gameRouter)
app.use('/admin', express.static('admin'))
app.use('/data', adminRouter)
app.use(middleware.errorHandler)
module.exports = app